name: build

on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: '0 0,12 * * *' # Runs every day at midnight and noon utc

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Python
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install .[dev]

      - name: Check formatting
        run: |
          source venv/bin/activate
          ./scripts/check_format.sh

      - name: Lint
        run: |
          source venv/bin/activate
          flake8 datadog_lambda/

  unit-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install .[dev]

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -vv
