name: Check Dependencies

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      #- name: Set up Python
      #  uses: actions/setup-python@v4

      - name: Check Dependencies
        run: ./scripts/check_dependencies.sh
