name: update-snapshots

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Node 14
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 14

      - name: Cache Node modules
        id: cache-node-modules
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install .[dev]

      - name: Install Serverless Framework
        run: sudo yarn global add serverless@^3.7.0 --prefix /usr/local
      - name: Install Crossbuild Deps
        run: |
          sudo apt-get update --allow-releaseinfo-change --fix-missing
          sudo apt install -y qemu-user-static binfmt-support

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        working-directory: tests/integration
        run: yarn install

      - name: Update Snapshots (amd64)
        env:
          ARCH: amd64
          UPDATE_SNAPSHOTS: true
          BUILD_LAYERS: true
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./scripts/run_integration_tests.sh

      - name: Update Snapshots (arm64)
        env:
          ARCH: arm64
          UPDATE_SNAPSHOTS: true
          BUILD_LAYERS: true
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./scripts/run_integration_tests.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3.14.0
        with:
          commit-message: update snapshots
          title: Update Snapshots
          body: |
            Autogenerated PR to update integration test snapshots. Make sure no difference when run in local environment before merging.
          branch: update-snapshots
